project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Quarto Exercise"
  site-url: "https://musa-550-fall-2023.github.io/MUSA550-website-template" 
  repo-url: https://github.com/MUSA-550-Fall-2023/MUSA550-website-template 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Hang Zhao, 2023"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://musa-550-fall-2023.github.io/
        text: "MUSA550 Course Website"
      - icon: github
        href: https://github.com/Cyanhang/MUSA550-website-template
        text: "MUSA 550 GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/hang-zhao-62060a1a9/
        text: "Hang Zhao Linkedin"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: Example.ipynb
        text: Example Notebook
      - href: Final-Project-Explore.ipynb
        text: Exploratory Analysis
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-python-code-blocks.qmd 
          - analysis/2-static-images.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




